matrix:
  include:
    #C with clang
    - os: linux
      language: c
      before_script:
        - wget https://download.savannah.gnu.org/releases/libgraph/libgraph-1.0.2.tar.gz
        - tar -xvf libgraph-1.0.2.tar.gz
        - pushd libgraph-1.0.2  && ./configure --prefix=/usr && make && sudo make install && popd
      script:
        make c
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libsdl1.2-dev
            - libsdl-image1.2 libsdl-image1.2-dev guile-1.8 guile-1.8-dev libsdl1.2debian libart-2.0-dev libaudiofile-dev libesd0-dev libdirectfb-dev libdirectfb-extra libfreetype6-dev libxext-dev x11proto-xext-dev libfreetype6 libaa1 libaa1-dev libslang2-dev libasound2 libasound2-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0"

    #C with gcc
    - os: linux
      language: c
      before_script:
        - wget https://download.savannah.gnu.org/releases/libgraph/libgraph-1.0.2.tar.gz
        - tar -xvf libgraph-1.0.2.tar.gz
        - pushd libgraph-1.0.2  && ./configure --prefix=/usr && make && sudo make install && popd
      script:
        make c
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - libsdl1.2-dev
            - libsdl-image1.2 libsdl-image1.2-dev guile-1.8 guile-1.8-dev libsdl1.2debian libart-2.0-dev libaudiofile-dev libesd0-dev libdirectfb-dev libdirectfb-extra libfreetype6-dev libxext-dev x11proto-xext-dev libfreetype6 libaa1 libaa1-dev libslang2-dev libasound2 libasound2-dev
      env:
        - MATRIX_EVAL="CC=gcc-7"

    #C++ with g++
    - os: linux
      language: cpp
      script:
        ./scripts/build_cpp.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    # Verify file name
    - os: linux
      language: python
      python:
        - "3.6"
      script:
        - pip install namanager
        - namanager -s third_party/namanager_settings.json --required

    # Check formatting of Python code
    - os: linux
      language: python
      python: 3.6
      script:
        - pip install black
        - ./scripts/python_code_style_checker.sh

    # Check formatting of Javascript code
    - os: linux
      language: node_js
      node_js: node
      script:
        - npm install -g prettier
        - ./scripts/javascript_code_style_checker.sh

before_install:
   - eval "${MATRIX_EVAL}"

addons:
  sonarcloud:
    organization: "bme-mit-iet-org"
    token:
      secure: "FxQDCs18eITG8aWaOBNN9bWSrNUi6BuFtY3fCAelLkM8ZTBTI+rgHP2tloLT/JcEmFhAsL5yQz5PrRs2x0OGBDAg5KWMVfVDnQ3AAglwAQ375zQZHT1fNBJHcAznTFJzU3b60X2H+gBkV3ENmrJxpphfgI8di7rPlx9eO2Sql0NEMBisLpXVo34nx9hdbFVf/Nup8JR9GlwmQkWFM0vVAnV7oHWmSDXPjMAWHb36guq3INGQgkGook8EjFQukjCw5iLLXyqeHBRpf/mnH0UTrlmwDiHq6BRtJdFQ+qOYkoAp6AYf887lw5tAORuR0+As3OI91UAqCRRWh92TlfaZ4iqIcQMX8jfraCMIQHfPmdpvL0TX/mRtteQMb1BS61jss4yzbIqkKxOaCVq+XKzkWtbQBvJPrnYyBwPjPCHrSg59Br0cNkLN08856c7CfWY8t2mDybgvuqOf22vVi6WYArZqrztkDSDtwrCtA0DuYCgpZ13isDxKM6qBhlhsC/EwUvrN9vzug544+eWE2e/lLE8R30N7VnREhanwsln4FdY0nDQeO/6kzHMaVjy8gQqHI8wk9qQSqwtaQvhBXVAlv6VpY9Z/y2JXib2K2JAK7azI9eS1BT7O5/Uc9i7guS6WLdEnPl/DiDLN95PI/plex/B8Qprhc8kuatnCN2JuTE8=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar